[package]
name = "OpenJonsson"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
macroquad = { version = "0.4.13", features = ["audio"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
