[package]
name = "OpenJonsson"
version = "0.2.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
macroquad = { version = "0.4.14", features = ["audio"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
